using System;
using System.Collections;
using System.Collections.Generic;
using DataCapture.Networking;
using UnityEngine;

namespace DataCapture.Testing
{
    [Serializable]
    public sealed class NetworkSendDebugLayer
    {
        // Temporary route: verify the Debug JPEG packet generated by VideoPacketSender.
        // This proves Unity-side packet creation/send was attempted. PC-side receipt
        // still needs external receiver evidence.

        [Header("Gate")]
        [SerializeField] private CaptureTransmissionGateSO transmissionGate;

        [Header("Network SOs")]
        [SerializeField] private NetworkSenderConfigurationSO networkConfiguration;
        [SerializeField] private CurrentNetworkPacketSO currentNetworkPacket;
        [SerializeField] private NetworkPacketQueueSO networkPacketQueue;

        public SODebugPacketBaseline CaptureBaseline()
        {
            return new SODebugPacketBaseline(
                networkPacketQueue != null ? networkPacketQueue.Count : 0,
                currentNetworkPacket != null ? currentNetworkPacket.sequenceId : -1,
                currentNetworkPacket != null ? currentNetworkPacket.frameId : -1);
        }

        public IEnumerator RunDebugImagePacket(
            MonoBehaviour owner,
            SODebugDebugImageObservation debugImage,
            SODebugPacketBaseline baseline,
            float timeoutSeconds,
            float pollIntervalSeconds,
            Action<bool> complete)
        {
            if (!debugImage.IsValid)
            {
                SODebugLog.Fail(
                    owner,
                    "NetworkSend.DebugImage",
                    "DebugImageObservation",
                    "valid DEBUG_JPEG output",
                    "invalid",
                    "Network packet cannot be checked because the debug image encoder did not produce a valid output.",
                    0f,
                    BuildFields(debugImage, baseline, false, default));
                complete(false);
                yield break;
            }

            float deadline = Time.unscaledTime + Mathf.Max(0.1f, timeoutSeconds);
            bool foundMatchingHeader = false;
            PacketTimestampHeader matchingHeader = default;
            string latestBlocker = string.Empty;

            while (Time.unscaledTime < deadline)
            {
                if (IsHealthy(debugImage, baseline, out foundMatchingHeader, out matchingHeader, out string fields, out latestBlocker))
                {
                    SODebugLog.Pass(owner, "NetworkSend.DebugImage", fields);
                    complete(true);
                    yield break;
                }

                yield return new WaitForSecondsRealtime(Mathf.Max(0.05f, pollIntervalSeconds));
            }

            IsHealthy(debugImage, baseline, out foundMatchingHeader, out matchingHeader, out string finalFields, out string finalBlocker);
            SODebugLog.Fail(
                owner,
                "NetworkSend.DebugImage",
                "NetworkPacketQueue",
                "matching video packet header for DEBUG_JPEG frame",
                BuildActual(foundMatchingHeader, matchingHeader),
                SODebugLog.FirstBlocker(latestBlocker, finalBlocker),
                timeoutSeconds,
                finalFields);
            complete(false);
        }

        private bool IsHealthy(
            SODebugDebugImageObservation debugImage,
            SODebugPacketBaseline baseline,
            out bool foundMatchingHeader,
            out PacketTimestampHeader matchingHeader,
            out string fields,
            out string blocker)
        {
            foundMatchingHeader = TryFindMatchingVideoHeader(debugImage, baseline, out matchingHeader);
            bool currentMatches = CurrentPacketMatches(debugImage, baseline);
            bool currentByteLengthOk = currentNetworkPacket != null &&
                currentNetworkPacket.byteLength > 0 &&
                (networkConfiguration == null || currentNetworkPacket.byteLength <= networkConfiguration.maxPacketBytes);

            fields = BuildFields(debugImage, baseline, foundMatchingHeader, matchingHeader);

            if (!CanUseNetworkConfiguration(out blocker))
            {
                return false;
            }

            if (transmissionGate != null && !transmissionGate.canEncodeAndSend)
            {
                blocker = "CaptureTransmissionGateSO.canEncodeAndSend is false: " + SODebugLog.Empty(transmissionGate.activeBlocker);
                return false;
            }

            if (debugImage.ByteLength >= networkConfiguration.maxPacketBytes)
            {
                blocker = "Debug JPEG byteLength is already >= maxPacketBytes before packet envelope overhead.";
                return false;
            }

            if (currentMatches && currentByteLengthOk)
            {
                blocker = string.Empty;
                return true;
            }

            if (foundMatchingHeader)
            {
                blocker = "Matching Debug JPEG video header exists in NetworkPacketQueue; CurrentNetworkPacket may have been overwritten by metadata after send.";
                return true;
            }

            if (networkPacketQueue != null && networkPacketQueue.Count > baseline.PacketQueueCount)
            {
                blocker = "NetworkPacketQueue grew, but no matching Debug JPEG video packet was found. Metadata may be sending while image sender is blocked.";
                return false;
            }

            if (currentNetworkPacket == null || !currentNetworkPacket.isValid)
            {
                blocker = "CurrentNetworkPacketSO is invalid. VideoPacketSender may be unassigned, sender not ready, or UDP TrySend returned false.";
                return false;
            }

            if (currentNetworkPacket.streamName != "video")
            {
                blocker = "CurrentNetworkPacketSO.streamName is " + SODebugLog.Empty(currentNetworkPacket.streamName) + ", expected video.";
                return false;
            }

            if (currentNetworkPacket.frameId != debugImage.SourceCameraFrameId)
            {
                blocker = "CurrentNetworkPacketSO.frameId does not match DEBUG_JPEG sourceCameraFrameId.";
                return false;
            }

            if (!currentByteLengthOk)
            {
                blocker = "CurrentNetworkPacketSO.byteLength is invalid or exceeds NetworkSenderConfigurationSO.maxPacketBytes.";
                return false;
            }

            blocker = "No Debug JPEG network packet has been recorded.";
            return false;
        }

        private bool CanUseNetworkConfiguration(out string blocker)
        {
            if (networkConfiguration == null)
            {
                blocker = "NetworkSenderConfigurationSO is not assigned.";
                return false;
            }

            if (!networkConfiguration.sendVideo)
            {
                blocker = "NetworkSenderConfigurationSO.sendVideo is false.";
                return false;
            }

            if (!networkConfiguration.UsesNetwork)
            {
                blocker = "NetworkSenderConfigurationSO.outputTarget does not use network transport.";
                return false;
            }

            if (string.IsNullOrWhiteSpace(networkConfiguration.ResolveHost()))
            {
                blocker = "NetworkSenderConfigurationSO.ResolveHost() is empty. PC discovery may not have written remoteHost.";
                return false;
            }

            if (networkConfiguration.ResolveVideoPort() <= 0 || networkConfiguration.ResolveVideoPort() > 65535)
            {
                blocker = "NetworkSenderConfigurationSO.ResolveVideoPort() is invalid.";
                return false;
            }

            if (networkConfiguration.maxPacketBytes <= 0)
            {
                blocker = "NetworkSenderConfigurationSO.maxPacketBytes is invalid.";
                return false;
            }

            blocker = string.Empty;
            return true;
        }

        private bool CurrentPacketMatches(SODebugDebugImageObservation debugImage, SODebugPacketBaseline baseline)
        {
            if (currentNetworkPacket == null || !currentNetworkPacket.isValid)
            {
                return false;
            }

            return currentNetworkPacket.streamName == "video" &&
                currentNetworkPacket.frameId == debugImage.SourceCameraFrameId &&
                currentNetworkPacket.timestampUnixMs == debugImage.TimestampUnixMs;
        }

        private bool TryFindMatchingVideoHeader(
            SODebugDebugImageObservation debugImage,
            SODebugPacketBaseline baseline,
            out PacketTimestampHeader header)
        {
            header = default;
            if (networkPacketQueue == null)
            {
                return false;
            }

            PacketTimestampHeader[] headers = networkPacketQueue.DebugSnapshot;
            if (headers == null || headers.Length == 0)
            {
                return false;
            }

            for (int i = headers.Length - 1; i >= 0; i--)
            {
                PacketTimestampHeader candidate = headers[i];
                if (candidate.streamName != "video")
                {
                    continue;
                }

                if (candidate.frameId != debugImage.SourceCameraFrameId)
                {
                    continue;
                }

                if (candidate.timestampUnixMs != debugImage.TimestampUnixMs)
                {
                    continue;
                }

                header = candidate;
                return true;
            }

            return false;
        }

        private string BuildFields(
            SODebugDebugImageObservation debugImage,
            SODebugPacketBaseline baseline,
            bool foundMatchingHeader,
            PacketTimestampHeader matchingHeader)
        {
            var parts = new List<string>
            {
                "debugImage.codec=" + SODebugLog.Empty(debugImage.Codec),
                "debugImage.sourceCameraFrameId=" + debugImage.SourceCameraFrameId,
                "debugImage.encodedFrameId=" + debugImage.EncodedFrameId,
                "debugImage.timestampUnixMs=" + debugImage.TimestampUnixMs,
                "debugImage.byteLength=" + debugImage.ByteLength,
                "debugImage.size=" + debugImage.Width + "x" + debugImage.Height,
                "gate.canEncodeAndSend=" + (transmissionGate != null ? SODebugLog.Bool(transmissionGate.canEncodeAndSend) : "null"),
                "gate.activeBlocker=" + SODebugLog.Empty(transmissionGate != null ? transmissionGate.activeBlocker : null),
                "currentPacket.isValid=" + (currentNetworkPacket != null ? SODebugLog.Bool(currentNetworkPacket.isValid) : "null"),
                "currentPacket.streamName=" + SODebugLog.Empty(currentNetworkPacket != null ? currentNetworkPacket.streamName : null),
                "currentPacket.frameId=" + (currentNetworkPacket != null ? currentNetworkPacket.frameId.ToString() : "null"),
                "currentPacket.timestampUnixMs=" + (currentNetworkPacket != null ? currentNetworkPacket.timestampUnixMs.ToString() : "null"),
                "currentPacket.sequenceId=" + (currentNetworkPacket != null ? currentNetworkPacket.sequenceId.ToString() : "null"),
                "currentPacket.byteLength=" + (currentNetworkPacket != null ? currentNetworkPacket.byteLength.ToString() : "null"),
                "packetQueue.count=" + (networkPacketQueue != null ? networkPacketQueue.Count.ToString() : "null"),
                "packetQueue.baselineCount=" + baseline.PacketQueueCount,
                "packetQueue.foundMatchingVideoHeader=" + SODebugLog.Bool(foundMatchingHeader),
                "matchingHeader.frameId=" + (foundMatchingHeader ? matchingHeader.frameId.ToString() : "null"),
                "matchingHeader.sequenceId=" + (foundMatchingHeader ? matchingHeader.sequenceId.ToString() : "null"),
                "matchingHeader.timestampUnixMs=" + (foundMatchingHeader ? matchingHeader.timestampUnixMs.ToString() : "null"),
                "config.outputTarget=" + (networkConfiguration != null ? networkConfiguration.outputTarget.ToString() : "null"),
                "config.usesNetwork=" + (networkConfiguration != null ? SODebugLog.Bool(networkConfiguration.UsesNetwork) : "null"),
                "config.sendVideo=" + (networkConfiguration != null ? SODebugLog.Bool(networkConfiguration.sendVideo) : "null"),
                "config.remoteHost=" + SODebugLog.Empty(networkConfiguration != null ? networkConfiguration.remoteHost : null),
                "config.resolvedHost=" + SODebugLog.Empty(networkConfiguration != null ? networkConfiguration.ResolveHost() : null),
                "config.resolvedVideoPort=" + (networkConfiguration != null ? networkConfiguration.ResolveVideoPort().ToString() : "null"),
                "config.maxPacketBytes=" + (networkConfiguration != null ? networkConfiguration.maxPacketBytes.ToString() : "null"),
                "config.receiverDiscovered=" + (networkConfiguration != null ? SODebugLog.Bool(networkConfiguration.receiverDiscovered) : "null"),
                "config.lastDiscoveryStatus=" + SODebugLog.Empty(networkConfiguration != null ? networkConfiguration.lastDiscoveryStatus : null),
                "config.networkWarning=" + SODebugLog.Empty(networkConfiguration != null ? networkConfiguration.networkWarning : null)
            };

            return string.Join("; ", parts);
        }

        private static string BuildActual(bool foundMatchingHeader, PacketTimestampHeader matchingHeader)
        {
            if (!foundMatchingHeader)
            {
                return "matchingDebugImageVideoHeader=False";
            }

            return "matchingDebugImageVideoHeader=True, frameId=" + matchingHeader.frameId +
                ", sequenceId=" + matchingHeader.sequenceId +
                ", timestampUnixMs=" + matchingHeader.timestampUnixMs;
        }
    }
}
